apiVersion: v1
kind: Pod
metadata:
  name: devops
  labels:
    app: my-app
spec:
  containers:
  - name: my-app
    image: suryanarayana070/t1-project:vigridtest
    ports:
    - containerPort: 9088
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 9088
      targetPort: 9088
  type: LoadBalancer
